### ISSUE TITLE
全站打包，安装后访问/admin报错

### ISSUE THREAD

**Issue by leorusLao** [e282486518/yii2admin#23]
环境php-7.1.1 nginx-1.10
使用全站打包
./yii install 安装后访问 /admin,报错如下

```
An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "public/404". in /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/web/ErrorHandler.php(97): yii\base\Module->runAction('public/404')
#1 /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "admin/login/login". in /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/login/log...', Array)
#1 /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(common\core\Request))
#2 /mnt/hgfs/yii/yii2admin/web/index.php(24): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /mnt/hgfs/yii/yii2admin/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(common\core\Request))
#1 /mnt/hgfs/yii/yii2admin/web/index.php(24): yii\base\Application->run()
#2 {main}
```

新手，请问如何解决，谢谢

**Comment by e282486518** [comment]
原因是你请求的地址有误，然后将你的请求导入了public/404 。
一般是重写问题，可以查考下 doc目录下的 nginx.conf文件。里面有单域名，多域名配置方式。
如果还是不行可以查考web目录 https://github.com/e282486518/yii2admin/blob/master/web/README.md 这里有说明。

**Comment by leorusLao** [comment]
解决了，非常感谢
